
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ChannelConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ChannelConfig
 * 
 */
export type ChannelConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$ChannelConfigPayload>

export type AggregateChannelConfig = {
  _count: ChannelConfigCountAggregateOutputType | null
  _min: ChannelConfigMinAggregateOutputType | null
  _max: ChannelConfigMaxAggregateOutputType | null
}

export type ChannelConfigMinAggregateOutputType = {
  id: string | null
  channel: string | null
  apiKey: string | null
  propertyId: string | null
  webhookSecret: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChannelConfigMaxAggregateOutputType = {
  id: string | null
  channel: string | null
  apiKey: string | null
  propertyId: string | null
  webhookSecret: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChannelConfigCountAggregateOutputType = {
  id: number
  channel: number
  apiKey: number
  propertyId: number
  webhookSecret: number
  active: number
  settings: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ChannelConfigMinAggregateInputType = {
  id?: true
  channel?: true
  apiKey?: true
  propertyId?: true
  webhookSecret?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ChannelConfigMaxAggregateInputType = {
  id?: true
  channel?: true
  apiKey?: true
  propertyId?: true
  webhookSecret?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ChannelConfigCountAggregateInputType = {
  id?: true
  channel?: true
  apiKey?: true
  propertyId?: true
  webhookSecret?: true
  active?: true
  settings?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ChannelConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChannelConfig to aggregate.
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChannelConfigs to fetch.
   */
  orderBy?: Prisma.ChannelConfigOrderByWithRelationInput | Prisma.ChannelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChannelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChannelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChannelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ChannelConfigs
  **/
  _count?: true | ChannelConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChannelConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChannelConfigMaxAggregateInputType
}

export type GetChannelConfigAggregateType<T extends ChannelConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateChannelConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChannelConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateChannelConfig[P]>
}




export type ChannelConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChannelConfigWhereInput
  orderBy?: Prisma.ChannelConfigOrderByWithAggregationInput | Prisma.ChannelConfigOrderByWithAggregationInput[]
  by: Prisma.ChannelConfigScalarFieldEnum[] | Prisma.ChannelConfigScalarFieldEnum
  having?: Prisma.ChannelConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChannelConfigCountAggregateInputType | true
  _min?: ChannelConfigMinAggregateInputType
  _max?: ChannelConfigMaxAggregateInputType
}

export type ChannelConfigGroupByOutputType = {
  id: string
  channel: string
  apiKey: string | null
  propertyId: string | null
  webhookSecret: string | null
  active: boolean
  settings: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: ChannelConfigCountAggregateOutputType | null
  _min: ChannelConfigMinAggregateOutputType | null
  _max: ChannelConfigMaxAggregateOutputType | null
}

export type GetChannelConfigGroupByPayload<T extends ChannelConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChannelConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChannelConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChannelConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChannelConfigGroupByOutputType[P]>
      }
    >
  >



export type ChannelConfigWhereInput = {
  AND?: Prisma.ChannelConfigWhereInput | Prisma.ChannelConfigWhereInput[]
  OR?: Prisma.ChannelConfigWhereInput[]
  NOT?: Prisma.ChannelConfigWhereInput | Prisma.ChannelConfigWhereInput[]
  id?: Prisma.StringFilter<"ChannelConfig"> | string
  channel?: Prisma.StringFilter<"ChannelConfig"> | string
  apiKey?: Prisma.StringNullableFilter<"ChannelConfig"> | string | null
  propertyId?: Prisma.StringNullableFilter<"ChannelConfig"> | string | null
  webhookSecret?: Prisma.StringNullableFilter<"ChannelConfig"> | string | null
  active?: Prisma.BoolFilter<"ChannelConfig"> | boolean
  settings?: Prisma.JsonNullableFilter<"ChannelConfig">
  createdAt?: Prisma.DateTimeFilter<"ChannelConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChannelConfig"> | Date | string
}

export type ChannelConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  apiKey?: Prisma.SortOrderInput | Prisma.SortOrder
  propertyId?: Prisma.SortOrderInput | Prisma.SortOrder
  webhookSecret?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  settings?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChannelConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  channel?: string
  AND?: Prisma.ChannelConfigWhereInput | Prisma.ChannelConfigWhereInput[]
  OR?: Prisma.ChannelConfigWhereInput[]
  NOT?: Prisma.ChannelConfigWhereInput | Prisma.ChannelConfigWhereInput[]
  apiKey?: Prisma.StringNullableFilter<"ChannelConfig"> | string | null
  propertyId?: Prisma.StringNullableFilter<"ChannelConfig"> | string | null
  webhookSecret?: Prisma.StringNullableFilter<"ChannelConfig"> | string | null
  active?: Prisma.BoolFilter<"ChannelConfig"> | boolean
  settings?: Prisma.JsonNullableFilter<"ChannelConfig">
  createdAt?: Prisma.DateTimeFilter<"ChannelConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChannelConfig"> | Date | string
}, "id" | "channel">

export type ChannelConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  apiKey?: Prisma.SortOrderInput | Prisma.SortOrder
  propertyId?: Prisma.SortOrderInput | Prisma.SortOrder
  webhookSecret?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  settings?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ChannelConfigCountOrderByAggregateInput
  _max?: Prisma.ChannelConfigMaxOrderByAggregateInput
  _min?: Prisma.ChannelConfigMinOrderByAggregateInput
}

export type ChannelConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChannelConfigScalarWhereWithAggregatesInput | Prisma.ChannelConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChannelConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChannelConfigScalarWhereWithAggregatesInput | Prisma.ChannelConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ChannelConfig"> | string
  channel?: Prisma.StringWithAggregatesFilter<"ChannelConfig"> | string
  apiKey?: Prisma.StringNullableWithAggregatesFilter<"ChannelConfig"> | string | null
  propertyId?: Prisma.StringNullableWithAggregatesFilter<"ChannelConfig"> | string | null
  webhookSecret?: Prisma.StringNullableWithAggregatesFilter<"ChannelConfig"> | string | null
  active?: Prisma.BoolWithAggregatesFilter<"ChannelConfig"> | boolean
  settings?: Prisma.JsonNullableWithAggregatesFilter<"ChannelConfig">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ChannelConfig"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ChannelConfig"> | Date | string
}

export type ChannelConfigCreateInput = {
  id?: string
  channel: string
  apiKey?: string | null
  propertyId?: string | null
  webhookSecret?: string | null
  active?: boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChannelConfigUncheckedCreateInput = {
  id?: string
  channel: string
  apiKey?: string | null
  propertyId?: string | null
  webhookSecret?: string | null
  active?: boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChannelConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  apiKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  propertyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  webhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChannelConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  apiKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  propertyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  webhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChannelConfigCreateManyInput = {
  id?: string
  channel: string
  apiKey?: string | null
  propertyId?: string | null
  webhookSecret?: string | null
  active?: boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChannelConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  apiKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  propertyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  webhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChannelConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  apiKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  propertyId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  webhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChannelConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  apiKey?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  webhookSecret?: Prisma.SortOrder
  active?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChannelConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  apiKey?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  webhookSecret?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChannelConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  apiKey?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  webhookSecret?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type ChannelConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channel?: boolean
  apiKey?: boolean
  propertyId?: boolean
  webhookSecret?: boolean
  active?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["channelConfig"]>

export type ChannelConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channel?: boolean
  apiKey?: boolean
  propertyId?: boolean
  webhookSecret?: boolean
  active?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["channelConfig"]>

export type ChannelConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channel?: boolean
  apiKey?: boolean
  propertyId?: boolean
  webhookSecret?: boolean
  active?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["channelConfig"]>

export type ChannelConfigSelectScalar = {
  id?: boolean
  channel?: boolean
  apiKey?: boolean
  propertyId?: boolean
  webhookSecret?: boolean
  active?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ChannelConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "channel" | "apiKey" | "propertyId" | "webhookSecret" | "active" | "settings" | "createdAt" | "updatedAt", ExtArgs["result"]["channelConfig"]>

export type $ChannelConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ChannelConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    channel: string
    apiKey: string | null
    propertyId: string | null
    webhookSecret: string | null
    active: boolean
    settings: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["channelConfig"]>
  composites: {}
}

export type ChannelConfigGetPayload<S extends boolean | null | undefined | ChannelConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload, S>

export type ChannelConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChannelConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChannelConfigCountAggregateInputType | true
  }

export interface ChannelConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ChannelConfig'], meta: { name: 'ChannelConfig' } }
  /**
   * Find zero or one ChannelConfig that matches the filter.
   * @param {ChannelConfigFindUniqueArgs} args - Arguments to find a ChannelConfig
   * @example
   * // Get one ChannelConfig
   * const channelConfig = await prisma.channelConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChannelConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, ChannelConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ChannelConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChannelConfigFindUniqueOrThrowArgs} args - Arguments to find a ChannelConfig
   * @example
   * // Get one ChannelConfig
   * const channelConfig = await prisma.channelConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChannelConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChannelConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChannelConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigFindFirstArgs} args - Arguments to find a ChannelConfig
   * @example
   * // Get one ChannelConfig
   * const channelConfig = await prisma.channelConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChannelConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, ChannelConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChannelConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigFindFirstOrThrowArgs} args - Arguments to find a ChannelConfig
   * @example
   * // Get one ChannelConfig
   * const channelConfig = await prisma.channelConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChannelConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChannelConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ChannelConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ChannelConfigs
   * const channelConfigs = await prisma.channelConfig.findMany()
   * 
   * // Get first 10 ChannelConfigs
   * const channelConfigs = await prisma.channelConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const channelConfigWithIdOnly = await prisma.channelConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChannelConfigFindManyArgs>(args?: Prisma.SelectSubset<T, ChannelConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ChannelConfig.
   * @param {ChannelConfigCreateArgs} args - Arguments to create a ChannelConfig.
   * @example
   * // Create one ChannelConfig
   * const ChannelConfig = await prisma.channelConfig.create({
   *   data: {
   *     // ... data to create a ChannelConfig
   *   }
   * })
   * 
   */
  create<T extends ChannelConfigCreateArgs>(args: Prisma.SelectSubset<T, ChannelConfigCreateArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ChannelConfigs.
   * @param {ChannelConfigCreateManyArgs} args - Arguments to create many ChannelConfigs.
   * @example
   * // Create many ChannelConfigs
   * const channelConfig = await prisma.channelConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChannelConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, ChannelConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ChannelConfigs and returns the data saved in the database.
   * @param {ChannelConfigCreateManyAndReturnArgs} args - Arguments to create many ChannelConfigs.
   * @example
   * // Create many ChannelConfigs
   * const channelConfig = await prisma.channelConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ChannelConfigs and only return the `id`
   * const channelConfigWithIdOnly = await prisma.channelConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChannelConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChannelConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ChannelConfig.
   * @param {ChannelConfigDeleteArgs} args - Arguments to delete one ChannelConfig.
   * @example
   * // Delete one ChannelConfig
   * const ChannelConfig = await prisma.channelConfig.delete({
   *   where: {
   *     // ... filter to delete one ChannelConfig
   *   }
   * })
   * 
   */
  delete<T extends ChannelConfigDeleteArgs>(args: Prisma.SelectSubset<T, ChannelConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ChannelConfig.
   * @param {ChannelConfigUpdateArgs} args - Arguments to update one ChannelConfig.
   * @example
   * // Update one ChannelConfig
   * const channelConfig = await prisma.channelConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChannelConfigUpdateArgs>(args: Prisma.SelectSubset<T, ChannelConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ChannelConfigs.
   * @param {ChannelConfigDeleteManyArgs} args - Arguments to filter ChannelConfigs to delete.
   * @example
   * // Delete a few ChannelConfigs
   * const { count } = await prisma.channelConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChannelConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChannelConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChannelConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ChannelConfigs
   * const channelConfig = await prisma.channelConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChannelConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, ChannelConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChannelConfigs and returns the data updated in the database.
   * @param {ChannelConfigUpdateManyAndReturnArgs} args - Arguments to update many ChannelConfigs.
   * @example
   * // Update many ChannelConfigs
   * const channelConfig = await prisma.channelConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ChannelConfigs and only return the `id`
   * const channelConfigWithIdOnly = await prisma.channelConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChannelConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChannelConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ChannelConfig.
   * @param {ChannelConfigUpsertArgs} args - Arguments to update or create a ChannelConfig.
   * @example
   * // Update or create a ChannelConfig
   * const channelConfig = await prisma.channelConfig.upsert({
   *   create: {
   *     // ... data to create a ChannelConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ChannelConfig we want to update
   *   }
   * })
   */
  upsert<T extends ChannelConfigUpsertArgs>(args: Prisma.SelectSubset<T, ChannelConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__ChannelConfigClient<runtime.Types.Result.GetResult<Prisma.$ChannelConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ChannelConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigCountArgs} args - Arguments to filter ChannelConfigs to count.
   * @example
   * // Count the number of ChannelConfigs
   * const count = await prisma.channelConfig.count({
   *   where: {
   *     // ... the filter for the ChannelConfigs we want to count
   *   }
   * })
  **/
  count<T extends ChannelConfigCountArgs>(
    args?: Prisma.Subset<T, ChannelConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChannelConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ChannelConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChannelConfigAggregateArgs>(args: Prisma.Subset<T, ChannelConfigAggregateArgs>): Prisma.PrismaPromise<GetChannelConfigAggregateType<T>>

  /**
   * Group by ChannelConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChannelConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChannelConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChannelConfigGroupByArgs['orderBy'] }
      : { orderBy?: ChannelConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChannelConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChannelConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ChannelConfig model
 */
readonly fields: ChannelConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ChannelConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChannelConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ChannelConfig model
 */
export interface ChannelConfigFieldRefs {
  readonly id: Prisma.FieldRef<"ChannelConfig", 'String'>
  readonly channel: Prisma.FieldRef<"ChannelConfig", 'String'>
  readonly apiKey: Prisma.FieldRef<"ChannelConfig", 'String'>
  readonly propertyId: Prisma.FieldRef<"ChannelConfig", 'String'>
  readonly webhookSecret: Prisma.FieldRef<"ChannelConfig", 'String'>
  readonly active: Prisma.FieldRef<"ChannelConfig", 'Boolean'>
  readonly settings: Prisma.FieldRef<"ChannelConfig", 'Json'>
  readonly createdAt: Prisma.FieldRef<"ChannelConfig", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ChannelConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ChannelConfig findUnique
 */
export type ChannelConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * Filter, which ChannelConfig to fetch.
   */
  where: Prisma.ChannelConfigWhereUniqueInput
}

/**
 * ChannelConfig findUniqueOrThrow
 */
export type ChannelConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * Filter, which ChannelConfig to fetch.
   */
  where: Prisma.ChannelConfigWhereUniqueInput
}

/**
 * ChannelConfig findFirst
 */
export type ChannelConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * Filter, which ChannelConfig to fetch.
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChannelConfigs to fetch.
   */
  orderBy?: Prisma.ChannelConfigOrderByWithRelationInput | Prisma.ChannelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChannelConfigs.
   */
  cursor?: Prisma.ChannelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChannelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChannelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChannelConfigs.
   */
  distinct?: Prisma.ChannelConfigScalarFieldEnum | Prisma.ChannelConfigScalarFieldEnum[]
}

/**
 * ChannelConfig findFirstOrThrow
 */
export type ChannelConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * Filter, which ChannelConfig to fetch.
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChannelConfigs to fetch.
   */
  orderBy?: Prisma.ChannelConfigOrderByWithRelationInput | Prisma.ChannelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChannelConfigs.
   */
  cursor?: Prisma.ChannelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChannelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChannelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChannelConfigs.
   */
  distinct?: Prisma.ChannelConfigScalarFieldEnum | Prisma.ChannelConfigScalarFieldEnum[]
}

/**
 * ChannelConfig findMany
 */
export type ChannelConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * Filter, which ChannelConfigs to fetch.
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChannelConfigs to fetch.
   */
  orderBy?: Prisma.ChannelConfigOrderByWithRelationInput | Prisma.ChannelConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ChannelConfigs.
   */
  cursor?: Prisma.ChannelConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChannelConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChannelConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChannelConfigs.
   */
  distinct?: Prisma.ChannelConfigScalarFieldEnum | Prisma.ChannelConfigScalarFieldEnum[]
}

/**
 * ChannelConfig create
 */
export type ChannelConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a ChannelConfig.
   */
  data: Prisma.XOR<Prisma.ChannelConfigCreateInput, Prisma.ChannelConfigUncheckedCreateInput>
}

/**
 * ChannelConfig createMany
 */
export type ChannelConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ChannelConfigs.
   */
  data: Prisma.ChannelConfigCreateManyInput | Prisma.ChannelConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ChannelConfig createManyAndReturn
 */
export type ChannelConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * The data used to create many ChannelConfigs.
   */
  data: Prisma.ChannelConfigCreateManyInput | Prisma.ChannelConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ChannelConfig update
 */
export type ChannelConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a ChannelConfig.
   */
  data: Prisma.XOR<Prisma.ChannelConfigUpdateInput, Prisma.ChannelConfigUncheckedUpdateInput>
  /**
   * Choose, which ChannelConfig to update.
   */
  where: Prisma.ChannelConfigWhereUniqueInput
}

/**
 * ChannelConfig updateMany
 */
export type ChannelConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ChannelConfigs.
   */
  data: Prisma.XOR<Prisma.ChannelConfigUpdateManyMutationInput, Prisma.ChannelConfigUncheckedUpdateManyInput>
  /**
   * Filter which ChannelConfigs to update
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * Limit how many ChannelConfigs to update.
   */
  limit?: number
}

/**
 * ChannelConfig updateManyAndReturn
 */
export type ChannelConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * The data used to update ChannelConfigs.
   */
  data: Prisma.XOR<Prisma.ChannelConfigUpdateManyMutationInput, Prisma.ChannelConfigUncheckedUpdateManyInput>
  /**
   * Filter which ChannelConfigs to update
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * Limit how many ChannelConfigs to update.
   */
  limit?: number
}

/**
 * ChannelConfig upsert
 */
export type ChannelConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the ChannelConfig to update in case it exists.
   */
  where: Prisma.ChannelConfigWhereUniqueInput
  /**
   * In case the ChannelConfig found by the `where` argument doesn't exist, create a new ChannelConfig with this data.
   */
  create: Prisma.XOR<Prisma.ChannelConfigCreateInput, Prisma.ChannelConfigUncheckedCreateInput>
  /**
   * In case the ChannelConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChannelConfigUpdateInput, Prisma.ChannelConfigUncheckedUpdateInput>
}

/**
 * ChannelConfig delete
 */
export type ChannelConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
  /**
   * Filter which ChannelConfig to delete.
   */
  where: Prisma.ChannelConfigWhereUniqueInput
}

/**
 * ChannelConfig deleteMany
 */
export type ChannelConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChannelConfigs to delete
   */
  where?: Prisma.ChannelConfigWhereInput
  /**
   * Limit how many ChannelConfigs to delete.
   */
  limit?: number
}

/**
 * ChannelConfig without action
 */
export type ChannelConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChannelConfig
   */
  select?: Prisma.ChannelConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChannelConfig
   */
  omit?: Prisma.ChannelConfigOmit<ExtArgs> | null
}
