
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ICalFeed` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ICalFeed
 * 
 */
export type ICalFeedModel = runtime.Types.Result.DefaultSelection<Prisma.$ICalFeedPayload>

export type AggregateICalFeed = {
  _count: ICalFeedCountAggregateOutputType | null
  _min: ICalFeedMinAggregateOutputType | null
  _max: ICalFeedMaxAggregateOutputType | null
}

export type ICalFeedMinAggregateOutputType = {
  id: string | null
  roomId: string | null
  platform: string | null
  url: string | null
  lastSync: Date | null
  lastError: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ICalFeedMaxAggregateOutputType = {
  id: string | null
  roomId: string | null
  platform: string | null
  url: string | null
  lastSync: Date | null
  lastError: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ICalFeedCountAggregateOutputType = {
  id: number
  roomId: number
  platform: number
  url: number
  lastSync: number
  lastError: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ICalFeedMinAggregateInputType = {
  id?: true
  roomId?: true
  platform?: true
  url?: true
  lastSync?: true
  lastError?: true
  createdAt?: true
  updatedAt?: true
}

export type ICalFeedMaxAggregateInputType = {
  id?: true
  roomId?: true
  platform?: true
  url?: true
  lastSync?: true
  lastError?: true
  createdAt?: true
  updatedAt?: true
}

export type ICalFeedCountAggregateInputType = {
  id?: true
  roomId?: true
  platform?: true
  url?: true
  lastSync?: true
  lastError?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ICalFeedAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ICalFeed to aggregate.
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ICalFeeds to fetch.
   */
  orderBy?: Prisma.ICalFeedOrderByWithRelationInput | Prisma.ICalFeedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ICalFeedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ICalFeeds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ICalFeeds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ICalFeeds
  **/
  _count?: true | ICalFeedCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ICalFeedMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ICalFeedMaxAggregateInputType
}

export type GetICalFeedAggregateType<T extends ICalFeedAggregateArgs> = {
      [P in keyof T & keyof AggregateICalFeed]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateICalFeed[P]>
    : Prisma.GetScalarType<T[P], AggregateICalFeed[P]>
}




export type ICalFeedGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ICalFeedWhereInput
  orderBy?: Prisma.ICalFeedOrderByWithAggregationInput | Prisma.ICalFeedOrderByWithAggregationInput[]
  by: Prisma.ICalFeedScalarFieldEnum[] | Prisma.ICalFeedScalarFieldEnum
  having?: Prisma.ICalFeedScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ICalFeedCountAggregateInputType | true
  _min?: ICalFeedMinAggregateInputType
  _max?: ICalFeedMaxAggregateInputType
}

export type ICalFeedGroupByOutputType = {
  id: string
  roomId: string
  platform: string
  url: string
  lastSync: Date | null
  lastError: string | null
  createdAt: Date
  updatedAt: Date
  _count: ICalFeedCountAggregateOutputType | null
  _min: ICalFeedMinAggregateOutputType | null
  _max: ICalFeedMaxAggregateOutputType | null
}

export type GetICalFeedGroupByPayload<T extends ICalFeedGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ICalFeedGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ICalFeedGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ICalFeedGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ICalFeedGroupByOutputType[P]>
      }
    >
  >



export type ICalFeedWhereInput = {
  AND?: Prisma.ICalFeedWhereInput | Prisma.ICalFeedWhereInput[]
  OR?: Prisma.ICalFeedWhereInput[]
  NOT?: Prisma.ICalFeedWhereInput | Prisma.ICalFeedWhereInput[]
  id?: Prisma.StringFilter<"ICalFeed"> | string
  roomId?: Prisma.StringFilter<"ICalFeed"> | string
  platform?: Prisma.StringFilter<"ICalFeed"> | string
  url?: Prisma.StringFilter<"ICalFeed"> | string
  lastSync?: Prisma.DateTimeNullableFilter<"ICalFeed"> | Date | string | null
  lastError?: Prisma.StringNullableFilter<"ICalFeed"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ICalFeed"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ICalFeed"> | Date | string
  room?: Prisma.XOR<Prisma.RoomScalarRelationFilter, Prisma.RoomWhereInput>
}

export type ICalFeedOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  roomId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  lastSync?: Prisma.SortOrderInput | Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  room?: Prisma.RoomOrderByWithRelationInput
}

export type ICalFeedWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  roomId_platform?: Prisma.ICalFeedRoomIdPlatformCompoundUniqueInput
  AND?: Prisma.ICalFeedWhereInput | Prisma.ICalFeedWhereInput[]
  OR?: Prisma.ICalFeedWhereInput[]
  NOT?: Prisma.ICalFeedWhereInput | Prisma.ICalFeedWhereInput[]
  roomId?: Prisma.StringFilter<"ICalFeed"> | string
  platform?: Prisma.StringFilter<"ICalFeed"> | string
  url?: Prisma.StringFilter<"ICalFeed"> | string
  lastSync?: Prisma.DateTimeNullableFilter<"ICalFeed"> | Date | string | null
  lastError?: Prisma.StringNullableFilter<"ICalFeed"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ICalFeed"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ICalFeed"> | Date | string
  room?: Prisma.XOR<Prisma.RoomScalarRelationFilter, Prisma.RoomWhereInput>
}, "id" | "roomId_platform">

export type ICalFeedOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  roomId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  lastSync?: Prisma.SortOrderInput | Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ICalFeedCountOrderByAggregateInput
  _max?: Prisma.ICalFeedMaxOrderByAggregateInput
  _min?: Prisma.ICalFeedMinOrderByAggregateInput
}

export type ICalFeedScalarWhereWithAggregatesInput = {
  AND?: Prisma.ICalFeedScalarWhereWithAggregatesInput | Prisma.ICalFeedScalarWhereWithAggregatesInput[]
  OR?: Prisma.ICalFeedScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ICalFeedScalarWhereWithAggregatesInput | Prisma.ICalFeedScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ICalFeed"> | string
  roomId?: Prisma.StringWithAggregatesFilter<"ICalFeed"> | string
  platform?: Prisma.StringWithAggregatesFilter<"ICalFeed"> | string
  url?: Prisma.StringWithAggregatesFilter<"ICalFeed"> | string
  lastSync?: Prisma.DateTimeNullableWithAggregatesFilter<"ICalFeed"> | Date | string | null
  lastError?: Prisma.StringNullableWithAggregatesFilter<"ICalFeed"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ICalFeed"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ICalFeed"> | Date | string
}

export type ICalFeedCreateInput = {
  id?: string
  platform: string
  url: string
  lastSync?: Date | string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  room: Prisma.RoomCreateNestedOneWithoutIcalFeedsInput
}

export type ICalFeedUncheckedCreateInput = {
  id?: string
  roomId: string
  platform: string
  url: string
  lastSync?: Date | string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ICalFeedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  room?: Prisma.RoomUpdateOneRequiredWithoutIcalFeedsNestedInput
}

export type ICalFeedUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roomId?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ICalFeedCreateManyInput = {
  id?: string
  roomId: string
  platform: string
  url: string
  lastSync?: Date | string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ICalFeedUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ICalFeedUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roomId?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ICalFeedListRelationFilter = {
  every?: Prisma.ICalFeedWhereInput
  some?: Prisma.ICalFeedWhereInput
  none?: Prisma.ICalFeedWhereInput
}

export type ICalFeedOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ICalFeedRoomIdPlatformCompoundUniqueInput = {
  roomId: string
  platform: string
}

export type ICalFeedCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roomId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  lastSync?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ICalFeedMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roomId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  lastSync?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ICalFeedMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roomId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  lastSync?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ICalFeedCreateNestedManyWithoutRoomInput = {
  create?: Prisma.XOR<Prisma.ICalFeedCreateWithoutRoomInput, Prisma.ICalFeedUncheckedCreateWithoutRoomInput> | Prisma.ICalFeedCreateWithoutRoomInput[] | Prisma.ICalFeedUncheckedCreateWithoutRoomInput[]
  connectOrCreate?: Prisma.ICalFeedCreateOrConnectWithoutRoomInput | Prisma.ICalFeedCreateOrConnectWithoutRoomInput[]
  createMany?: Prisma.ICalFeedCreateManyRoomInputEnvelope
  connect?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
}

export type ICalFeedUncheckedCreateNestedManyWithoutRoomInput = {
  create?: Prisma.XOR<Prisma.ICalFeedCreateWithoutRoomInput, Prisma.ICalFeedUncheckedCreateWithoutRoomInput> | Prisma.ICalFeedCreateWithoutRoomInput[] | Prisma.ICalFeedUncheckedCreateWithoutRoomInput[]
  connectOrCreate?: Prisma.ICalFeedCreateOrConnectWithoutRoomInput | Prisma.ICalFeedCreateOrConnectWithoutRoomInput[]
  createMany?: Prisma.ICalFeedCreateManyRoomInputEnvelope
  connect?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
}

export type ICalFeedUpdateManyWithoutRoomNestedInput = {
  create?: Prisma.XOR<Prisma.ICalFeedCreateWithoutRoomInput, Prisma.ICalFeedUncheckedCreateWithoutRoomInput> | Prisma.ICalFeedCreateWithoutRoomInput[] | Prisma.ICalFeedUncheckedCreateWithoutRoomInput[]
  connectOrCreate?: Prisma.ICalFeedCreateOrConnectWithoutRoomInput | Prisma.ICalFeedCreateOrConnectWithoutRoomInput[]
  upsert?: Prisma.ICalFeedUpsertWithWhereUniqueWithoutRoomInput | Prisma.ICalFeedUpsertWithWhereUniqueWithoutRoomInput[]
  createMany?: Prisma.ICalFeedCreateManyRoomInputEnvelope
  set?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  disconnect?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  delete?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  connect?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  update?: Prisma.ICalFeedUpdateWithWhereUniqueWithoutRoomInput | Prisma.ICalFeedUpdateWithWhereUniqueWithoutRoomInput[]
  updateMany?: Prisma.ICalFeedUpdateManyWithWhereWithoutRoomInput | Prisma.ICalFeedUpdateManyWithWhereWithoutRoomInput[]
  deleteMany?: Prisma.ICalFeedScalarWhereInput | Prisma.ICalFeedScalarWhereInput[]
}

export type ICalFeedUncheckedUpdateManyWithoutRoomNestedInput = {
  create?: Prisma.XOR<Prisma.ICalFeedCreateWithoutRoomInput, Prisma.ICalFeedUncheckedCreateWithoutRoomInput> | Prisma.ICalFeedCreateWithoutRoomInput[] | Prisma.ICalFeedUncheckedCreateWithoutRoomInput[]
  connectOrCreate?: Prisma.ICalFeedCreateOrConnectWithoutRoomInput | Prisma.ICalFeedCreateOrConnectWithoutRoomInput[]
  upsert?: Prisma.ICalFeedUpsertWithWhereUniqueWithoutRoomInput | Prisma.ICalFeedUpsertWithWhereUniqueWithoutRoomInput[]
  createMany?: Prisma.ICalFeedCreateManyRoomInputEnvelope
  set?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  disconnect?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  delete?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  connect?: Prisma.ICalFeedWhereUniqueInput | Prisma.ICalFeedWhereUniqueInput[]
  update?: Prisma.ICalFeedUpdateWithWhereUniqueWithoutRoomInput | Prisma.ICalFeedUpdateWithWhereUniqueWithoutRoomInput[]
  updateMany?: Prisma.ICalFeedUpdateManyWithWhereWithoutRoomInput | Prisma.ICalFeedUpdateManyWithWhereWithoutRoomInput[]
  deleteMany?: Prisma.ICalFeedScalarWhereInput | Prisma.ICalFeedScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ICalFeedCreateWithoutRoomInput = {
  id?: string
  platform: string
  url: string
  lastSync?: Date | string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ICalFeedUncheckedCreateWithoutRoomInput = {
  id?: string
  platform: string
  url: string
  lastSync?: Date | string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ICalFeedCreateOrConnectWithoutRoomInput = {
  where: Prisma.ICalFeedWhereUniqueInput
  create: Prisma.XOR<Prisma.ICalFeedCreateWithoutRoomInput, Prisma.ICalFeedUncheckedCreateWithoutRoomInput>
}

export type ICalFeedCreateManyRoomInputEnvelope = {
  data: Prisma.ICalFeedCreateManyRoomInput | Prisma.ICalFeedCreateManyRoomInput[]
  skipDuplicates?: boolean
}

export type ICalFeedUpsertWithWhereUniqueWithoutRoomInput = {
  where: Prisma.ICalFeedWhereUniqueInput
  update: Prisma.XOR<Prisma.ICalFeedUpdateWithoutRoomInput, Prisma.ICalFeedUncheckedUpdateWithoutRoomInput>
  create: Prisma.XOR<Prisma.ICalFeedCreateWithoutRoomInput, Prisma.ICalFeedUncheckedCreateWithoutRoomInput>
}

export type ICalFeedUpdateWithWhereUniqueWithoutRoomInput = {
  where: Prisma.ICalFeedWhereUniqueInput
  data: Prisma.XOR<Prisma.ICalFeedUpdateWithoutRoomInput, Prisma.ICalFeedUncheckedUpdateWithoutRoomInput>
}

export type ICalFeedUpdateManyWithWhereWithoutRoomInput = {
  where: Prisma.ICalFeedScalarWhereInput
  data: Prisma.XOR<Prisma.ICalFeedUpdateManyMutationInput, Prisma.ICalFeedUncheckedUpdateManyWithoutRoomInput>
}

export type ICalFeedScalarWhereInput = {
  AND?: Prisma.ICalFeedScalarWhereInput | Prisma.ICalFeedScalarWhereInput[]
  OR?: Prisma.ICalFeedScalarWhereInput[]
  NOT?: Prisma.ICalFeedScalarWhereInput | Prisma.ICalFeedScalarWhereInput[]
  id?: Prisma.StringFilter<"ICalFeed"> | string
  roomId?: Prisma.StringFilter<"ICalFeed"> | string
  platform?: Prisma.StringFilter<"ICalFeed"> | string
  url?: Prisma.StringFilter<"ICalFeed"> | string
  lastSync?: Prisma.DateTimeNullableFilter<"ICalFeed"> | Date | string | null
  lastError?: Prisma.StringNullableFilter<"ICalFeed"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ICalFeed"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ICalFeed"> | Date | string
}

export type ICalFeedCreateManyRoomInput = {
  id?: string
  platform: string
  url: string
  lastSync?: Date | string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ICalFeedUpdateWithoutRoomInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ICalFeedUncheckedUpdateWithoutRoomInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ICalFeedUncheckedUpdateManyWithoutRoomInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ICalFeedSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roomId?: boolean
  platform?: boolean
  url?: boolean
  lastSync?: boolean
  lastError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  room?: boolean | Prisma.RoomDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iCalFeed"]>

export type ICalFeedSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roomId?: boolean
  platform?: boolean
  url?: boolean
  lastSync?: boolean
  lastError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  room?: boolean | Prisma.RoomDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iCalFeed"]>

export type ICalFeedSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roomId?: boolean
  platform?: boolean
  url?: boolean
  lastSync?: boolean
  lastError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  room?: boolean | Prisma.RoomDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iCalFeed"]>

export type ICalFeedSelectScalar = {
  id?: boolean
  roomId?: boolean
  platform?: boolean
  url?: boolean
  lastSync?: boolean
  lastError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ICalFeedOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "roomId" | "platform" | "url" | "lastSync" | "lastError" | "createdAt" | "updatedAt", ExtArgs["result"]["iCalFeed"]>
export type ICalFeedInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  room?: boolean | Prisma.RoomDefaultArgs<ExtArgs>
}
export type ICalFeedIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  room?: boolean | Prisma.RoomDefaultArgs<ExtArgs>
}
export type ICalFeedIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  room?: boolean | Prisma.RoomDefaultArgs<ExtArgs>
}

export type $ICalFeedPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ICalFeed"
  objects: {
    room: Prisma.$RoomPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    roomId: string
    platform: string
    url: string
    lastSync: Date | null
    lastError: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["iCalFeed"]>
  composites: {}
}

export type ICalFeedGetPayload<S extends boolean | null | undefined | ICalFeedDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload, S>

export type ICalFeedCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ICalFeedFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ICalFeedCountAggregateInputType | true
  }

export interface ICalFeedDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ICalFeed'], meta: { name: 'ICalFeed' } }
  /**
   * Find zero or one ICalFeed that matches the filter.
   * @param {ICalFeedFindUniqueArgs} args - Arguments to find a ICalFeed
   * @example
   * // Get one ICalFeed
   * const iCalFeed = await prisma.iCalFeed.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ICalFeedFindUniqueArgs>(args: Prisma.SelectSubset<T, ICalFeedFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ICalFeed that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ICalFeedFindUniqueOrThrowArgs} args - Arguments to find a ICalFeed
   * @example
   * // Get one ICalFeed
   * const iCalFeed = await prisma.iCalFeed.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ICalFeedFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ICalFeedFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ICalFeed that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedFindFirstArgs} args - Arguments to find a ICalFeed
   * @example
   * // Get one ICalFeed
   * const iCalFeed = await prisma.iCalFeed.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ICalFeedFindFirstArgs>(args?: Prisma.SelectSubset<T, ICalFeedFindFirstArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ICalFeed that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedFindFirstOrThrowArgs} args - Arguments to find a ICalFeed
   * @example
   * // Get one ICalFeed
   * const iCalFeed = await prisma.iCalFeed.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ICalFeedFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ICalFeedFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ICalFeeds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ICalFeeds
   * const iCalFeeds = await prisma.iCalFeed.findMany()
   * 
   * // Get first 10 ICalFeeds
   * const iCalFeeds = await prisma.iCalFeed.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const iCalFeedWithIdOnly = await prisma.iCalFeed.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ICalFeedFindManyArgs>(args?: Prisma.SelectSubset<T, ICalFeedFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ICalFeed.
   * @param {ICalFeedCreateArgs} args - Arguments to create a ICalFeed.
   * @example
   * // Create one ICalFeed
   * const ICalFeed = await prisma.iCalFeed.create({
   *   data: {
   *     // ... data to create a ICalFeed
   *   }
   * })
   * 
   */
  create<T extends ICalFeedCreateArgs>(args: Prisma.SelectSubset<T, ICalFeedCreateArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ICalFeeds.
   * @param {ICalFeedCreateManyArgs} args - Arguments to create many ICalFeeds.
   * @example
   * // Create many ICalFeeds
   * const iCalFeed = await prisma.iCalFeed.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ICalFeedCreateManyArgs>(args?: Prisma.SelectSubset<T, ICalFeedCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ICalFeeds and returns the data saved in the database.
   * @param {ICalFeedCreateManyAndReturnArgs} args - Arguments to create many ICalFeeds.
   * @example
   * // Create many ICalFeeds
   * const iCalFeed = await prisma.iCalFeed.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ICalFeeds and only return the `id`
   * const iCalFeedWithIdOnly = await prisma.iCalFeed.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ICalFeedCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ICalFeedCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ICalFeed.
   * @param {ICalFeedDeleteArgs} args - Arguments to delete one ICalFeed.
   * @example
   * // Delete one ICalFeed
   * const ICalFeed = await prisma.iCalFeed.delete({
   *   where: {
   *     // ... filter to delete one ICalFeed
   *   }
   * })
   * 
   */
  delete<T extends ICalFeedDeleteArgs>(args: Prisma.SelectSubset<T, ICalFeedDeleteArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ICalFeed.
   * @param {ICalFeedUpdateArgs} args - Arguments to update one ICalFeed.
   * @example
   * // Update one ICalFeed
   * const iCalFeed = await prisma.iCalFeed.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ICalFeedUpdateArgs>(args: Prisma.SelectSubset<T, ICalFeedUpdateArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ICalFeeds.
   * @param {ICalFeedDeleteManyArgs} args - Arguments to filter ICalFeeds to delete.
   * @example
   * // Delete a few ICalFeeds
   * const { count } = await prisma.iCalFeed.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ICalFeedDeleteManyArgs>(args?: Prisma.SelectSubset<T, ICalFeedDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ICalFeeds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ICalFeeds
   * const iCalFeed = await prisma.iCalFeed.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ICalFeedUpdateManyArgs>(args: Prisma.SelectSubset<T, ICalFeedUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ICalFeeds and returns the data updated in the database.
   * @param {ICalFeedUpdateManyAndReturnArgs} args - Arguments to update many ICalFeeds.
   * @example
   * // Update many ICalFeeds
   * const iCalFeed = await prisma.iCalFeed.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ICalFeeds and only return the `id`
   * const iCalFeedWithIdOnly = await prisma.iCalFeed.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ICalFeedUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ICalFeedUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ICalFeed.
   * @param {ICalFeedUpsertArgs} args - Arguments to update or create a ICalFeed.
   * @example
   * // Update or create a ICalFeed
   * const iCalFeed = await prisma.iCalFeed.upsert({
   *   create: {
   *     // ... data to create a ICalFeed
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ICalFeed we want to update
   *   }
   * })
   */
  upsert<T extends ICalFeedUpsertArgs>(args: Prisma.SelectSubset<T, ICalFeedUpsertArgs<ExtArgs>>): Prisma.Prisma__ICalFeedClient<runtime.Types.Result.GetResult<Prisma.$ICalFeedPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ICalFeeds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedCountArgs} args - Arguments to filter ICalFeeds to count.
   * @example
   * // Count the number of ICalFeeds
   * const count = await prisma.iCalFeed.count({
   *   where: {
   *     // ... the filter for the ICalFeeds we want to count
   *   }
   * })
  **/
  count<T extends ICalFeedCountArgs>(
    args?: Prisma.Subset<T, ICalFeedCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ICalFeedCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ICalFeed.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ICalFeedAggregateArgs>(args: Prisma.Subset<T, ICalFeedAggregateArgs>): Prisma.PrismaPromise<GetICalFeedAggregateType<T>>

  /**
   * Group by ICalFeed.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ICalFeedGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ICalFeedGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ICalFeedGroupByArgs['orderBy'] }
      : { orderBy?: ICalFeedGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ICalFeedGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetICalFeedGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ICalFeed model
 */
readonly fields: ICalFeedFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ICalFeed.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ICalFeedClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  room<T extends Prisma.RoomDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoomDefaultArgs<ExtArgs>>): Prisma.Prisma__RoomClient<runtime.Types.Result.GetResult<Prisma.$RoomPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ICalFeed model
 */
export interface ICalFeedFieldRefs {
  readonly id: Prisma.FieldRef<"ICalFeed", 'String'>
  readonly roomId: Prisma.FieldRef<"ICalFeed", 'String'>
  readonly platform: Prisma.FieldRef<"ICalFeed", 'String'>
  readonly url: Prisma.FieldRef<"ICalFeed", 'String'>
  readonly lastSync: Prisma.FieldRef<"ICalFeed", 'DateTime'>
  readonly lastError: Prisma.FieldRef<"ICalFeed", 'String'>
  readonly createdAt: Prisma.FieldRef<"ICalFeed", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ICalFeed", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ICalFeed findUnique
 */
export type ICalFeedFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * Filter, which ICalFeed to fetch.
   */
  where: Prisma.ICalFeedWhereUniqueInput
}

/**
 * ICalFeed findUniqueOrThrow
 */
export type ICalFeedFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * Filter, which ICalFeed to fetch.
   */
  where: Prisma.ICalFeedWhereUniqueInput
}

/**
 * ICalFeed findFirst
 */
export type ICalFeedFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * Filter, which ICalFeed to fetch.
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ICalFeeds to fetch.
   */
  orderBy?: Prisma.ICalFeedOrderByWithRelationInput | Prisma.ICalFeedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ICalFeeds.
   */
  cursor?: Prisma.ICalFeedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ICalFeeds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ICalFeeds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ICalFeeds.
   */
  distinct?: Prisma.ICalFeedScalarFieldEnum | Prisma.ICalFeedScalarFieldEnum[]
}

/**
 * ICalFeed findFirstOrThrow
 */
export type ICalFeedFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * Filter, which ICalFeed to fetch.
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ICalFeeds to fetch.
   */
  orderBy?: Prisma.ICalFeedOrderByWithRelationInput | Prisma.ICalFeedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ICalFeeds.
   */
  cursor?: Prisma.ICalFeedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ICalFeeds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ICalFeeds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ICalFeeds.
   */
  distinct?: Prisma.ICalFeedScalarFieldEnum | Prisma.ICalFeedScalarFieldEnum[]
}

/**
 * ICalFeed findMany
 */
export type ICalFeedFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * Filter, which ICalFeeds to fetch.
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ICalFeeds to fetch.
   */
  orderBy?: Prisma.ICalFeedOrderByWithRelationInput | Prisma.ICalFeedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ICalFeeds.
   */
  cursor?: Prisma.ICalFeedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ICalFeeds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ICalFeeds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ICalFeeds.
   */
  distinct?: Prisma.ICalFeedScalarFieldEnum | Prisma.ICalFeedScalarFieldEnum[]
}

/**
 * ICalFeed create
 */
export type ICalFeedCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * The data needed to create a ICalFeed.
   */
  data: Prisma.XOR<Prisma.ICalFeedCreateInput, Prisma.ICalFeedUncheckedCreateInput>
}

/**
 * ICalFeed createMany
 */
export type ICalFeedCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ICalFeeds.
   */
  data: Prisma.ICalFeedCreateManyInput | Prisma.ICalFeedCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ICalFeed createManyAndReturn
 */
export type ICalFeedCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * The data used to create many ICalFeeds.
   */
  data: Prisma.ICalFeedCreateManyInput | Prisma.ICalFeedCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ICalFeed update
 */
export type ICalFeedUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * The data needed to update a ICalFeed.
   */
  data: Prisma.XOR<Prisma.ICalFeedUpdateInput, Prisma.ICalFeedUncheckedUpdateInput>
  /**
   * Choose, which ICalFeed to update.
   */
  where: Prisma.ICalFeedWhereUniqueInput
}

/**
 * ICalFeed updateMany
 */
export type ICalFeedUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ICalFeeds.
   */
  data: Prisma.XOR<Prisma.ICalFeedUpdateManyMutationInput, Prisma.ICalFeedUncheckedUpdateManyInput>
  /**
   * Filter which ICalFeeds to update
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * Limit how many ICalFeeds to update.
   */
  limit?: number
}

/**
 * ICalFeed updateManyAndReturn
 */
export type ICalFeedUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * The data used to update ICalFeeds.
   */
  data: Prisma.XOR<Prisma.ICalFeedUpdateManyMutationInput, Prisma.ICalFeedUncheckedUpdateManyInput>
  /**
   * Filter which ICalFeeds to update
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * Limit how many ICalFeeds to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ICalFeed upsert
 */
export type ICalFeedUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * The filter to search for the ICalFeed to update in case it exists.
   */
  where: Prisma.ICalFeedWhereUniqueInput
  /**
   * In case the ICalFeed found by the `where` argument doesn't exist, create a new ICalFeed with this data.
   */
  create: Prisma.XOR<Prisma.ICalFeedCreateInput, Prisma.ICalFeedUncheckedCreateInput>
  /**
   * In case the ICalFeed was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ICalFeedUpdateInput, Prisma.ICalFeedUncheckedUpdateInput>
}

/**
 * ICalFeed delete
 */
export type ICalFeedDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
  /**
   * Filter which ICalFeed to delete.
   */
  where: Prisma.ICalFeedWhereUniqueInput
}

/**
 * ICalFeed deleteMany
 */
export type ICalFeedDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ICalFeeds to delete
   */
  where?: Prisma.ICalFeedWhereInput
  /**
   * Limit how many ICalFeeds to delete.
   */
  limit?: number
}

/**
 * ICalFeed without action
 */
export type ICalFeedDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICalFeed
   */
  select?: Prisma.ICalFeedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICalFeed
   */
  omit?: Prisma.ICalFeedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICalFeedInclude<ExtArgs> | null
}
